name: moreira_app
description: Cliente Flutter para Taller de Motos Moreira
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  path_provider: ^2.0.0
  open_file: ^3.2.1
  file_picker: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  # Include app assets so logo is bundled in release APK
  assets:
    - assets/logo.png

# Configuration for flutter_launcher_icons to set the Android launcher icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
